name: project_get
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  intl: ^0.18.1
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.9.0

dev_dependencies: 
  flutter_lints: 2.0.2
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

